server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://122.51.76.113:3306/mysql
    username: root
    password: xj20170721

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
